# Generated by Django 3.0.7 on 2020-06-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_slider',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
